#version eksctl 0.191.0 or higher

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

# Specify desired availability zones. Don't forget to update the 'metadata.region' parameter to match availability zones.
availabilityZones: [us-east-2a, us-east-2b, us-east-2c]

metadata:
  name: thingsboard
  region: us-east-2
  version: '1.32'

iam:
  withOIDC: false
  podIdentityAssociations:
    - serviceAccountName: aws-load-balancer-controller
      namespace: kube-system
      roleName: Thingsboard-EKS-ALB-Role
      permissionPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSLoadBalancingPolicy
      createServiceAccount: true

iamIdentityMappings:
  - arn: arn:aws:iam::844062109895:user/AWS-Developer
    username: AWS-Developer
    groups:
      - system:masters
  - arn: arn:aws:iam::844062109895:user/TheHuman
    username: TheHuman
    groups:
      - system:masters

managedNodeGroups:
  - name: tb-node
    instanceType: t3.medium
    desiredCapacity: 2
    maxSize: 3
    minSize: 2
    labels: { role: tb-node }
    privateNetworking: true
    volumeType: gp3
    volumeSize: 20
    ssh:
      allow: true
      publicKeyPath: 'ec2_login_key'

addonsConfig:
  autoApplyPodIdentityAssociations: true

addons:
  - name: eks-pod-identity-agent
    version: latest

  - name: kube-proxy
    version: latest

  - name: aws-ebs-csi-driver

  - name: vpc-cni
    version: latest
